name: Deploy ReactApp to EC2 Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: 🟢 Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        working-directory: ./
        run: |
          npm ci --legacy-peer-deps

      - name: Build
        working-directory: ./
        run: |
          npm run build
      
      - name: Setup SSH Key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEV_KEY }}
          EC2_HOST: ${{ secrets.DEV_HOST }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" | base64 --decode > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts

      - name: Copy build on server
        env:
          EC2_HOST: ${{ secrets.DEV_HOST }}
          EC2_USER: ${{ secrets.DEV_USER }}
        run: |
          # Upload build to a temporary directory on the server
          rsync -avz --delete -e "ssh -i ~/.ssh/id_rsa" \
            ./dist/ $EC2_USER@$EC2_HOST:/tmp/temp-build/

          # Atomic deployment
          ssh -i ~/.ssh/id_rsa $EC2_USER@$EC2_HOST << 'EOF'
            sudo mkdir -p /var/www/html/web/demo-react/

             # Backup current deployment
            if [ -d "/var/www/html/web/demo-react" ]; then
              sudo rm -rf /var/www/html/web/demo-react-backup
              sudo cp -R /var/www/html/web/demo-react /var/www/html/web/demo-react-backup
            fi

            # Replace deployment
            sudo rsync -av --delete /tmp/temp-build/ /var/www/html/web/demo-react/

            # Permissions
            sudo chown -R www-data:www-data /var/www/html/web/demo-react/
            sudo chmod -R 755 /var/www/html/web/demo-react/

            # Cleanup
            rm -rf /tmp/temp-build/
          EOF
